(function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},f="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};f.Symbol||(f.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function l(){k();var a=f.Symbol.iterator;a||(a=f.Symbol.iterator=f.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){l();a={next:a};a[f.Symbol.iterator]=function(){return this};return a}
function n(a){if(!(a instanceof Array)){l();var b=a[Symbol.iterator];a=b?b.call(a):m(a);for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function ea(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
var p=window.Element.prototype,q=p.matches||p.matchesSelector||p.webkitMatchesSelector||p.mozMatchesSelector||p.msMatchesSelector||p.oMatchesSelector;function r(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||t(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||t(a,d))return!0}return!1}function t(a,b){if("string"!=typeof b)return!1;if(q)return q.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}
function fa(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function u(a,b,c){function d(a){var d;if(h.composed&&"function"==typeof a.composedPath)for(var e=a.composedPath(),g=0,D;D=e[g];g++)1==D.nodeType&&r(D,b)&&(d=D);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(fa(d)),e=0;g=d[e];e++)if(r(g,b)){d=g;break a}d=void 0}d&&c.call(d,a,d)}var e=document,h={composed:!0,B:!0},h=void 0===h?{}:h;e.addEventListener(a,d,h.B);return{i:function(){e.removeEventListener(a,d,h.B)}}}
function ha(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(!a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var ia=/:(80|443)$/,v=document.createElement("a"),w={};
function x(a){a=a&&"."!=a?a:location.href;if(w[a])return w[a];v.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return x(v.href);var b="80"==v.port||"443"==v.port?"":v.port,b="0"==b?"":b,c=v.host.replace(ia,"");return w[a]={hash:v.hash,host:c,hostname:v.hostname,href:v.href,origin:v.origin?v.origin:v.protocol+"//"+c,pathname:"/"==v.pathname.charAt(0)?v.pathname:"/"+v.pathname,port:b,protocol:v.protocol,search:v.search}}var y=[];
function z(a,b){var c=this;this.context=a;this.v=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.b=[];this.a=[];this.g=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.a[c.a.length-1].apply(null,[].concat(n(b)))};this.c?a.set(b,this.g):a[b]=this.g}function A(a,b,c){a=ja(a,b);a.b.push(c);ka(a)}function B(a,b,c){a=ja(a,b);c=a.b.indexOf(c);-1<c&&(a.b.splice(c,1),0<a.b.length?ka(a):a.i())}
function ka(a){a.a=[];for(var b,c=0;b=a.b[c];c++){var d=a.a[c-1]||a.f.bind(a.context);a.a.push(b(d))}}z.prototype.i=function(){var a=y.indexOf(this);-1<a&&(y.splice(a,1),this.c?this.context.set(this.v,this.f):this.context[this.v]=this.f)};function ja(a,b){var c=y.filter(function(c){return c.context==a&&c.v==b})[0];c||(c=new z(a,b),y.push(c));return c}
function C(a,b,c,d,e,h){if("function"==typeof d){var g=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,e,h);g(c)}}}return E({},a,b)}function la(a,b){var c=ha(a),d={};Object.keys(c).forEach(function(a){if(!a.indexOf(b)&&a!=b+"on"){var e=c[a];"true"==e&&(e=!0);"false"==e&&(e=!1);a=ma(a.slice(b.length));d[a]=e}});return d}
function na(a){var b;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];clearTimeout(b);b=setTimeout(function(){return a.apply(null,[].concat(n(d)))},500)}}function oa(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}var F={};
function pa(a,b){function c(){clearTimeout(e.timeout);e.send&&B(a,"send",e.send);delete F[d];e.A.forEach(function(a){return a()})}var d=a.get("trackingId"),e=F[d]=F[d]||{};clearTimeout(e.timeout);e.timeout=setTimeout(c,0);e.A=e.A||[];e.A.push(b);e.send||(e.send=function(a){return function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c();a.apply(null,[].concat(n(d)))}},A(a,"send",e.send))}
var E=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var d=0,e=c.length;d<e;d++){var h=Object(c[d]),g;for(g in h)Object.prototype.hasOwnProperty.call(h,g)&&(a[g]=h[g])}return a};function ma(a){return a.replace(/[\-\_]+(\w?)/g,function(a,c){return c.toUpperCase()})}
function G(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}function qa(){this.a={}}function ra(a,b){(a.a.externalSet=a.a.externalSet||[]).push(b)}
qa.prototype.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];(this.a[a]=this.a[a]||[]).forEach(function(a){return a.apply(null,[].concat(n(c)))})};var H={},I=!1,J;function K(a,b){b=void 0===b?{}:b;this.a={};this.b=a;this.m=b;this.h=null}ea(K,qa);function L(a,b,c){a=["autotrack",a,b].join(":");H[a]||(H[a]=new K(a,c),I||(window.addEventListener("storage",sa),I=!0));return H[a]}
function M(){if(null!=J)return J;try{window.localStorage.setItem("autotrack","autotrack"),window.localStorage.removeItem("autotrack"),J=!0}catch(a){J=!1}return J}K.prototype.get=function(){if(this.h)return this.h;if(M())try{this.h=N(window.localStorage.getItem(this.b))}catch(a){}return this.h=E({},this.m,this.h)};K.prototype.set=function(a){this.h=E({},this.m,this.h,a);if(M())try{var b=JSON.stringify(this.h);window.localStorage.setItem(this.b,b)}catch(c){}};
function ta(a){a.h={};if(M())try{window.localStorage.removeItem(a.b)}catch(b){}}K.prototype.i=function(){delete H[this.b];Object.keys(H).length||(window.removeEventListener("storage",sa),I=!1)};function sa(a){var b=H[a.key];if(b){var c=E({},b.m,N(a.oldValue));a=E({},b.m,N(a.newValue));b.h=a;b.I("externalSet",a,c)}}function N(a){var b={};if(a)try{b=JSON.parse(a)}catch(c){}return b}var ua={};
function O(a,b,c){this.f=a;this.timeout=b||P;this.timeZone=c;this.b=this.b.bind(this);A(a,"sendHitTask",this.b);try{this.c=new Intl.DateTimeFormat("en-US",{timeZone:this.timeZone})}catch(d){}this.a=L(a.get("trackingId"),"session",{hitTime:0,isExpired:!1})}O.prototype.isExpired=function(a){a=a?a:this.a.get();if(a.isExpired)return!0;var b=new Date,c=(a=a.hitTime)&&new Date(a);return a&&(b-c>6E4*this.timeout||this.c&&this.c.format(b)!=this.c.format(c))?!0:!1};
O.prototype.b=function(a){var b=this;return function(c){a(c);var d=b.a.get(),e=b.isExpired(d);c=c.get("sessionControl");d.hitTime=+new Date;if("start"==c||e)d.isExpired=!1;"end"==c&&(d.isExpired=!0);b.a.set(d)}};O.prototype.i=function(){B(this.f,"sendHitTask",this.b);this.a.i();delete ua[this.f.get("trackingId")]};var P=30,Q={C:1,K:2,L:3,M:4,F:5,G:6,H:7,N:8,O:9,D:10},R=Object.keys(Q).length;
function S(a,b){a.set("\x26_av","2.3.2");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<R)for(var d=R-c.length;d;)c="0"+c,d--;b=R-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}
function T(a,b){S(a,Q.D);window.addEventListener&&(this.a=E({increaseThreshold:20,sessionTimeout:P,fieldsObj:{}},b),this.c=a,this.b=va(this),this.f=na(this.f.bind(this)),this.j=this.j.bind(this),this.g=L(a.get("trackingId"),"plugins/max-scroll-tracker"),this.l=new O(a,this.a.sessionTimeout,this.a.timeZone),A(a,"set",this.j),wa(this))}function wa(a){100>(a.g.get()[a.b]||0)&&window.addEventListener("scroll",a.f)}
T.prototype.f=function(){var a=document.documentElement,b=document.body,a=Math.min(100,Math.max(0,Math.round(window.pageYOffset/(Math.max(a.offsetHeight,a.scrollHeight,b.offsetHeight,b.scrollHeight)-window.innerHeight)*100)));if(this.l.isExpired())ta(this.g);else if(b=this.g.get()[this.b]||0,a>b&&(100!=a&&100!=b||window.removeEventListener("scroll",this.f),b=a-b,100==a||b>=this.a.increaseThreshold)){var c={};this.g.set((c[this.b]=a,c));a={transport:"beacon",eventCategory:"Max Scroll",eventAction:"increase",
eventValue:b,eventLabel:String(a),nonInteraction:!0};this.a.maxScrollMetricIndex&&(a["metric"+this.a.maxScrollMetricIndex]=b);this.c.send("event",C(a,this.a.fieldsObj,this.c,this.a.hitFilter))}};T.prototype.j=function(a){var b=this;return function(c,d){a(c,d);var e={};("object"==typeof c&&null!==c?c:(e[c]=d,e)).page&&(c=b.b,b.b=va(b),b.b!=c&&wa(b))}};function va(a){a=x(a.c.get("page")||a.c.get("location"));return a.pathname+a.search}
T.prototype.remove=function(){this.l.i();window.removeEventListener("scroll",this.f);B(this.c,"set",this.j)};G("maxScrollTracker",T);var U=function xa(b){return b?(b^16*Math.random()>>b/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,xa)}();
function V(a,b){var c=this;S(a,Q.H);document.visibilityState&&(this.a=E({sessionTimeout:P,visibleThreshold:5E3,sendInitialPageview:!1,fieldsObj:{}},b),this.b=a,this.o=this.g=null,this.w=!1,this.j=this.j.bind(this),this.f=this.f.bind(this),this.l=this.l.bind(this),this.u=this.u.bind(this),this.c=L(a.get("trackingId"),"plugins/page-visibility-tracker"),ra(this.c,this.u),this.s=new O(a,this.a.sessionTimeout,this.a.timeZone),A(a,"set",this.j),window.addEventListener("unload",this.l),document.addEventListener("visibilitychange",
this.f),this.f(),pa(this.b,function(){if("visible"==document.visibilityState)c.a.sendInitialPageview&&(W(c,{J:!0}),c.w=!0);else if(c.a.sendInitialPageview&&c.a.pageLoadsMetricIndex){var a={},a=(a.transport="beacon",a.eventCategory="Page Visibility",a.eventAction="page load",a.eventLabel="(not set)",a["metric"+c.a.pageLoadsMetricIndex]=1,a.nonInteraction=!0,a);c.b.send("event",C(a,c.a.fieldsObj,c.b,c.a.hitFilter))}}))}
V.prototype.f=function(){var a=this;if("visible"==document.visibilityState||"hidden"==document.visibilityState){var b=ya(this,this.c.get()),c={time:+new Date,state:document.visibilityState,pageId:U};this.g&&"visible"==document.visibilityState&&this.a.sendInitialPageview&&!this.w&&(W(this),this.w=!0);this.o&&"hidden"==document.visibilityState&&clearTimeout(this.o);this.s.isExpired()?"hidden"==this.g&&"visible"==document.visibilityState?(clearTimeout(this.o),this.o=setTimeout(function(){a.c.set(c);
W(a,{hitTime:c.time})},this.a.visibleThreshold)):"hidden"==document.visibilityState&&ta(this.c):(b.pageId==U&&"visible"==b.state&&za(this,b),this.c.set(c));this.g=document.visibilityState}};function ya(a,b){"visible"==a.g&&"hidden"==b.state&&b.pageId!=U&&(b.state="visible",b.pageId=U,a.c.set(b));return b}
function za(a,b,c){c=(c?c:{}).hitTime;var d={hitTime:c},d=(d?d:{}).hitTime;(b=b.time&&!a.s.isExpired()?(d||+new Date)-b.time:0)&&b>=a.a.visibleThreshold&&(b=Math.round(b/1E3),d={transport:"beacon",nonInteraction:!0,eventCategory:"Page Visibility",eventAction:"track",eventValue:b,eventLabel:"(not set)"},c&&(d.queueTime=+new Date-c),a.a.visibleMetricIndex&&(d["metric"+a.a.visibleMetricIndex]=b),a.b.send("event",C(d,a.a.fieldsObj,a.b,a.a.hitFilter)))}
function W(a,b){var c=b?b:{};b=c.hitTime;var c=c.J,d={transport:"beacon"};b&&(d.queueTime=+new Date-b);c&&a.a.pageLoadsMetricIndex&&(d["metric"+a.a.pageLoadsMetricIndex]=1);a.b.send("pageview",C(d,a.a.fieldsObj,a.b,a.a.hitFilter))}V.prototype.j=function(a){var b=this;return function(c,d){var e={},e="object"==typeof c&&null!==c?c:(e[c]=d,e);e.page&&e.page!==b.b.get("page")&&"visible"==b.g&&b.f();a(c,d)}};V.prototype.u=function(a,b){a.time!=b.time&&b.pageId==U&&"visible"==b.state&&za(this,b,{hitTime:a.time})};
V.prototype.l=function(){"hidden"!=this.g&&this.f()};V.prototype.remove=function(){this.c.i();this.s.i();B(this.b,"set",this.j);window.removeEventListener("unload",this.l);document.removeEventListener("visibilitychange",this.f)};G("pageVisibilityTracker",V);
function X(a,b){var c=this;S(a,Q.G);window.addEventListener&&(this.a=E({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.f=a,this.c=this.c.bind(this),this.b={},this.a.events.forEach(function(a){c.b[a]=u(a,c.a.linkSelector,c.c)}))}
X.prototype.c=function(a,b){if(this.a.shouldTrackOutboundLink(b,x)){var c=b.getAttribute("href")||b.getAttribute("xlink:href"),d=x(c),e={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:d.href};navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which||window.addEventListener("click",function(a){a.defaultPrevented||(a.preventDefault(),e.hitCallback=oa(function(){location.href=c}))});d=E({},this.a.fieldsObj,la(b,this.a.attributePrefix));
this.f.send("event",C(e,d,this.f,this.a.hitFilter,b,a))}};X.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};X.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].i()})};G("outboundLinkTracker",X);
function Y(a,b){S(a,Q.F);window.addEventListener&&(this.a=E({formSelector:"form",shouldTrackOutboundForm:this.shouldTrackOutboundForm,fieldsObj:{},attributePrefix:"ga-"},b),this.b=a,this.c=u("submit",this.a.formSelector,this.f.bind(this)))}
Y.prototype.f=function(a,b){var c={transport:"beacon",eventCategory:"Outbound Form",eventAction:"submit",eventLabel:x(b.action).href};if(this.a.shouldTrackOutboundForm(b,x)){navigator.sendBeacon||(a.preventDefault(),c.hitCallback=oa(function(){b.submit()}));var d=E({},this.a.fieldsObj,la(b,this.a.attributePrefix));this.b.send("event",C(c,d,this.b,this.a.hitFilter,b,a))}};
Y.prototype.shouldTrackOutboundForm=function(a,b){a=b(a.action);return a.hostname!=location.hostname&&"http"==a.protocol.slice(0,4)};Y.prototype.remove=function(){this.c.i()};G("outboundFormTracker",Y);function Z(a,b){S(a,Q.C);this.a=E({},b);this.g=a;this.b=this.a.stripQuery&&this.a.queryDimensionIndex?"dimension"+this.a.queryDimensionIndex:null;this.f=this.f.bind(this);this.c=this.c.bind(this);A(a,"get",this.f);A(a,"buildHitTask",this.c)}
Z.prototype.f=function(a){var b=this;return function(c){if("page"==c||c==b.b){var d={location:a("location"),page:a("page")};return Aa(b,d)[c]}return a(c)}};Z.prototype.c=function(a){var b=this;return function(c){var d=Aa(b,{location:c.get("location"),page:c.get("page")});c.set(d,null,!0);a(c)}};
function Aa(a,b){var c=x(b.page||b.location),d=c.pathname;if(a.a.indexFilename){var e=d.split("/");a.a.indexFilename==e[e.length-1]&&(e[e.length-1]="",d=e.join("/"))}"remove"==a.a.trailingSlash?d=d.replace(/\/+$/,""):"add"==a.a.trailingSlash&&(/\.\w+$/.test(d)||"/"==d.substr(-1)||(d+="/"));d={page:d+(a.a.stripQuery?"":c.search)};b.location&&(d.location=b.location);a.b&&(d[a.b]=c.search.slice(1)||"(not set)");return"function"==typeof a.a.urlFieldsFilter?(b=a.a.urlFieldsFilter(d,x),c={},c.page=b.page,
c.location=b.location,c[a.b]=b[a.b],c):d}Z.prototype.remove=function(){B(this.g,"get",this.f);B(this.g,"buildHitTask",this.c)};G("cleanUrlTracker",Z);})();
//# sourceMappingURL=autotrack.js.map